### ISSUE TITLE
Custom Collection for non-enumeration Terms

### ISSUE THREAD

**Issue by asladeofgreen** [ES-DOC/pyessv#1]
Some DRS facets are not an enumeration of allowed values but refers to a “pattern” or a combination of other facets:
Examples:
CMIP6 Ensemble -> r[0-9]i[0-9]p[0-9]f[0-9]  
CORDEX RCM Model ->   [institute]-[rcm_name]  

Add a custom RegExCollection instance that would not have term files but rather a regular expression to constrain term names within the collection.
Add a custom CombineCollection instance that would not have term files but rather a collections uid pattern to build term names from other collections.
Those custom collection should be able to propagate the validation/check methods depending on the RegEx or the terms from the other collections.

**Comment by glevava** [comment]
First case is supported by `term_regex`.
Second case of "composed" collection is more tricky because it needs combinations restrictions.
e.g., IPSL-HIRCHAM5 doesn't yet exist.
