### ISSUE TITLE
Takes a long time to load the PYESSV archive files

### ISSUE THREAD

**Issue by agstephens** [ES-DOC/pyessv#16]
Hi @momipsl - hope you are well :-)

I have been loading the CMIP6 pyessv-archive and note it takes from 20-40 seconds on my system, E.g.:

```
$ time python -c 'import pyessv'
2020-07-21 10:42:20.492009 [INFO] :: PYESSV :: Loading vocabularies from /vagrant-share/amf-compliance-checker-work-2020/pyessv-archive:
2020-07-21 10:42:41.567366 [INFO] :: PYESSV :: ... loaded: wcrp

real    0m21.706s
user    0m0.980s
sys     0m6.994s
```

Do you see a similar performance? If so, have you thought about ways of optimising the loading process?

**Comment by momipsl** [comment]
@agstephens can you please confirm which version of python you are running and also which version of pyessv ?

**Comment by agstephens** [comment]
User error! It was only slow on my VM. Works fine elsewhere.
