### ISSUE TITLE
Add contributor guidelines via a CONTRIBUTING file

### ISSUE THREAD

**Issue by sadielbartholomew** [ES-DOC/pyessv#18]
A support email has requested that we add contributor guidelines to the codebase, with the following context:

> I would like to ask if an OSI-endorsed license could be added to this repo (and contributor guidelines, Ideally). It would be immensely useful to be able to extend the existing work with additions, or be able to maintain a fork that we could use to expand on existing controlled vocabularies as well as receive upstream changes.

(See also #17 which covers the licensing aspect separately.)

Once we have agreed some suitable guidance to set, it can be registered simply and in a standardised way via the GitHub `CONTRIBUTING.md` file to be added in the repo root. (Alternatively we can register the same guidelines across all ES-DOC repos via the equivalent file in the [special `.github` repo](https://github.com/ES-DOC/.github) I set up a while back.)

**Comment by asladeofgreen** [comment]
Inspiration from: https://mozillascience.github.io/working-open-workshop/contributing/
