### ISSUE TITLE
Validate term name - simple case

### ISSUE THREAD

**Issue by asladeofgreen** [ES-DOC/pyessv#2]
Validate term name, E.G.:

```
institutions = load_collection('wcrp', 'cmip6', 'institution-id')
institutions.has_term('IPSL')
```

**Comment by momipsl** [comment]
1.  Valid name
2.  Valid reformatted name
3.  Valid alternative name
4.  Valid synonym

institutions = load_collection('wcrp', 'cmip6', 'institution-id')
institutions.is_member('IPSL', strict=True)

**Comment by momipsl** [comment]
If target collection is RegExCollection then:

1.  Validate name against regular expression.

    E.G. ensemble-variant: r%(digit)si%(digit)sp%(digit)s

2.  Validate name against combination:

    E.G. CORDEX RCM Model: [institute]-[rcm_name]

**Comment by momipsl** [comment]
If target collection is CombinationCollection then validate name against combination:

    E.G. CORDEX RCM Model: [institute]-[rcm_name]

**Comment by momipsl** [comment]
Dataset identifier example: 

dataset_id = cmip5.%(product)s.%(institute)s.%(model)s.%(experiment)s.%(time_frequency)s.%(realm)s.%(cmor_table)s.%(ensemble)s

Becomes a regular expression:

cmip5.[esgf.global.product].[wcrp.global.institute] ...etc
