### ISSUE TITLE
Add DRS info at Scope level

### ISSUE THREAD

**Issue by asladeofgreen** [ES-DOC/pyessv#4]
Add DRS info at the Scope level about dataset ID, directory and filename format, through the MANIFEST:
Example:
```
cmip6 = pyesdoc.cv.load_scope('wcrp', 'cmip6')
print cmip6.data['dataset_id_template']
print cmip6.data['directory_format']
print cmip6.data['filename_format']
```

**Comment by momipsl** [comment]
Scope class will gain an extra attribute, data, allowing scope creator to associate arbitrary information with a scope.

**Comment by glevava** [comment]
Done in PR
