### ISSUE TITLE
Validate term name - regex

### ISSUE THREAD

**Issue by asladeofgreen** [ES-DOC/pyessv#6]
If target collection is RegExCollection then validate name against regular expression.

E.G. ensemble-variant: r%(digit)si%(digit)sp%(digit)s
Note that the above is not a pure regular expression but an 'ESG' regex, equivalent pure regular expression is: r[0-9]+i[0-9]+p[0-9]+

This is fairly simple as the Collection class can be extended with a regex that is applied at the point of term creation / validation.

**Comment by momipsl** [comment]
ESG INI patterns:

filename_format = %(variable)s_%(cmor_table)s_%(model)s_%(experiment)s_%(ensemble)s[_%(period_start)s-%(period_end)s].nc

directory_format = %(root)s/%(project)s/%(product)s/%(institute)s/%(model)s/%(experiment)s/%(time_frequency)s/%(realm)s/%(cmor_table)s/%(ensemble)s/%(version)s/%(variable)s

dataset_id = cmip5.%(product)s.%(institute)s.%(model)s.%(experiment)s.%(time_frequency)s.%(realm)s.%(cmor_table)s.%(ensemble)s

Become regular expressions:

cmip5.[esgf.global.product].[wcrp.global.institute] ...etc
